sonar.projectKey=NamalTharindu97_nomnom-lk
sonar.organization=namaltharindu97
sonar.host.url=https://sonarcloud.io

# Go
sonar.go.coverage.reportPaths=backend/coverage.out
sonar.go.tests.reportPaths=backend/report.xml

# Admin (JS/TS)
sonar.javascript.lcov.reportPaths=admin/coverage/lcov.info
sonar.sources=admin/src
sonar.tests=admin/tests

# Flutter (Dart)
sonar.dart.coverage.reportPaths=flutter/coverage/lcov.info
